PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE TblCommand(
   CmdID INTEGER PRIMARY KEY,
   Cmd BYTE NOT NULL,
   cmnt TEXT,
   date DATE
);
CREATE TABLE TblTagContent(
   TagID INTEGER PRIMARY KEY,
   Tag TEXT NOT NULL
);
CREATE TABLE TblTagMap(
   ID INTEGER PRIMARY KEY,
   TagID INT NOT NULL,
   CmdID INT NOT NULL
);
CREATE TABLE TblRefMap(
   ID INTEGER PRIMARY KEY,
   RefID INT NOT NULL,
   CmdID INT NOT NULL
);
CREATE TABLE TblRefContent(
   ID INTEGER PRIMARY KEY,
   Ref TEXT NOT NULL
);
CREATE TABLE TblUpdates(
   UpdateID INTEGER PRIMARY KEY,
   hash TEXT NOT NULL,
   URL TEXT,
   date DATE
);
COMMIT;
